name: Personal Portofolio 🚀

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_OCEAN_0947D1210
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "reactapp" # Directory containing package.json
          api_location: "" # No API in this project
          output_location: "reactapp/build" # Built app output directory

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_OCEAN_0947D1210
          action: "close"
